### ISSUE TITLE
_subsample_with_geojson is not producing Cloud Optimized GeoTIFF

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#240]
`_subsample_with_geojson` from #217 is not outputting a COG file. And our util to convert to COG is not converting that output.

We need to implement a way to do subsampling with a GeoJSON feature that will output the image in COG format

**Comment by banesullivan** [comment]
Currently, I am using rasterio and a mask to perform the cut but this can also be done with `gdal.Warp`. I have the code set up to do this in https://github.com/ResonantGeoData/ResonantGeoData/pull/243/commits/f7792b0d7409400c12bbca9cf954745d21f62830 but it is currently throwing an odd error:

```
celery_1    | [2021-01-14 17:48:50,795: ERROR/ForkPoolWorker-1] rgd.geodata.tasks.task_populate_subsampled_image[0bcfe992-4d69-42d7-acd0-78e23288d7b4]: Internal error run `populate_subsampled_image`: object of wrong GDALDatasetShadow
celery_1    | Traceback (most recent call last):
celery_1    |   File "/opt/django-project/rgd/geodata/tasks.py", line 15, in _safe_execution
celery_1    |     func(*args, **kwargs)
celery_1    |   File "/opt/django-project/rgd/geodata/models/imagery/subsample.py", line 124, in populate_subsampled_image
celery_1    |     _subsample_with_geojson(source_field, subsampled.data.file, kwargs, prefix='subsampled_')
celery_1    |   File "/opt/django-project/rgd/geodata/models/imagery/subsample.py", line 88, in _subsample_with_geojson
celery_1    |     ds = gdal.Warp(output_path, file_path, cutlineDSName=geojson_path)
celery_1    |   File "/usr/local/lib/python3.8/site-packages/osgeo/gdal.py", line 691, in Warp
celery_1    |     return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
celery_1    |   File "/usr/local/lib/python3.8/site-packages/osgeo/gdal.py", line 4480, in wrapper_GDALWarpDestName
celery_1    |     return _gdal.wrapper_GDALWarpDestName(*args)
celery_1    | TypeError: object of wrong GDALDatasetShadow
```

**Comment by banesullivan** [comment]
I use `gdal.Warp` (same code as linked above) locally, I can convert that output to COG format

**Comment by banesullivan** [comment]
I'm closing this issue in favor of no longer creating masked rasters and letting `large_image` handle returning image ROIs. See #295 for progress
