### ISSUE TITLE
clean_file_cache utility failing on files that are cleaned by other processes/threads

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#596]
```
Traceback (most recent call last):
File "/web-apps/ResonantGeoData/django-rgd/rgd/tasks/helpers.py", line 11, in _safe_execution
func(*args, **kwargs)
File "/web-apps/ResonantGeoData/django-rgd-imagery/rgd_imagery/tasks/etl.py", line 87, in load_image
_populate_image_meta_models(image, image_meta)
File "/web-apps/ResonantGeoData/django-rgd-imagery/rgd_imagery/tasks/etl.py", line 36, in _populate_image_meta_models
with yeild_tilesource_from_image(image) as tile_source:
File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
return next(self.gen)
File "/web-apps/ResonantGeoData/django-rgd-imagery/rgd_imagery/large_image_utilities.py", line 27, in yeild_tilesource_from_image
yield get_tilesource_from_image(image, projection)
File "/web-apps/ResonantGeoData/django-rgd-imagery/rgd_imagery/large_image_utilities.py", line 20, in get_tilesource_from_image
with image.file.yield_local_path(yield_file_set=True) as file_path:
File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
return next(self.gen)
File "/web-apps/ResonantGeoData/django-rgd/rgd/models/file.py", line 274, in yield_local_path
path = self.download_to_local_path()
File "/web-apps/ResonantGeoData/django-rgd/rgd/models/file.py", line 214, in download_to_local_path
clean_file_cache()
File "/web-apps/ResonantGeoData/django-rgd/rgd/utility.py", line 301, in clean_file_cache
paths = sorted(Path(cache).iterdir(), key=os.path.getmtime) # This sorts oldest to latest
File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/rgd/file_cache/LC08_L2SP_187022_20190427_20211102_02_T1_T35ULA_SEA4.tif.aux.xml'
```

To mitigate this, we need to check out single files under a directory like we do for FileSets. An easy solution to this would be to make `FileSet` non-nullable

**Comment by banesullivan** [comment]
Actually, the real problem here is that `clean_file_cache` is not thread/proccess safe. Speciffically:

https://github.com/ResonantGeoData/ResonantGeoData/blob/7dd577eb089be437c420fa5ef34d00b33a205ded/django-rgd/rgd/utility.py#L301

The iter will grab a file and another thread could delete it before the sort evaluates `os.path.getmtime`
